version: "3.9"

services:
  scheduler:
    # build: .
    image: ghcr.io/ryaneggz/scheduler:latest
    container_name: scheduler
    env_file:
      - .env
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    restart: unless-stopped 